### ISSUE TITLE
ModuleNotFoundError: No module named 'poselib.skeleton.backend.fbx'

### ISSUE THREAD

**Issue by VineetTambe** [chengxuxin/expressive-humanoid#1]
I have followed the "fbx-sdk" and "fbx-python-binding" installation as described in the link provided in the  [README](https://github.com/nv-tlabs/ASE/issues/61) - however I get the following error when I run `fbx_importer.py` in `ASE/ase/poselib`

Could the authors tell me how they export the system variables after fbx is installed such that the package is available everywhere?

The error I am getting is:
```
2024-07-16 22:15:51,188 - INFO - logger - logger initialized
Traceback (most recent call last):
  File "fbx_importer.py", line 43, in <module>
    motion = SkeletonMotion.from_fbx(
  File "/home/user/expressive-humanoid/ASE/ase/poselib/poselib/skeleton/skeleton3d.py", line 1236, in from_fbx
    from .backend.fbx.fbx_read_wrapper import fbx_to_array
ModuleNotFoundError: No module named 'poselib.skeleton.backend.fbx'
```

Have I missed any steps which are causing fbs import issues in `fpx_importer.py` ?

Thanks!

**Comment by 66Lau** [comment]
I meet same problem, because there are noting in path 'poselib.skeleton.backend',

But I found these files in other repo https://github.com/T-K-233/PoseLib/tree/main/poselib/skeleton/backend/fbx, maybe miss the files like in this

**Comment by chengxuxin** [comment]
It is a gitignore bug and it should have been fixed in the latest commit.

**Comment by VineetTambe** [comment]
Thanks! 
I am able to import `fbx` now!
But generate `generate_amp_humanoid_tpose.py` does not render anything in the figure that generates. 
Am I missing something?

**Comment by xiaohu-art** [comment]
I am sorry but I followed the instruction to install fbx but got error "ModuleNotFoundError: No module named 'fbxsip'"
