### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/pkl/motions_autogen_all_no_run_jump.pkl'

### ISSUE THREAD

**Issue by dbdxnuliba** [chengxuxin/expressive-humanoid#10]
(humanoid) nuli@nuli:~/rl/expressive-humanoid/legged_gym/legged_gym/scripts$ python train.py 000-01-some_descriptions_of_run --device cuda:0 --entity WANDB_ENTITY

Loading 775/780 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/91_34.npy
Loading 776/780 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/91_35.npy
Loading 777/780 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/91_36.npy
Loading 778/780 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/91_57.npy
Loading 779/780 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/91_62.npy
Loading 780/780 motion files: /home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/retarget_npy/93_07.npy
Loaded 780 motions with a total length of 13390.549s.
Traceback (most recent call last):
  File "/home/nuli/rl/expressive-humanoid/ASE/ase/utils/motion_lib.py", line 110, in __init__
    self.deserialize_motions(pkl_file)
  File "/home/nuli/rl/expressive-humanoid/ASE/ase/utils/motion_lib.py", line 362, in deserialize_motions
    with open(pkl_file, 'rb') as inp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/pkl/motions_autogen_all_no_run_jump.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 74, in <module>
    train(args)
  File "train.py", line 67, in train
    env, env_cfg = task_registry.make_env(name=args.task, args=args)
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/utils/task_registry.py", line 98, in make_env
    env = task_class(   cfg=env_cfg,
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 43, in __init__
    self.init_motions(cfg)
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 118, in init_motions
    self._load_motion(motion_file, cfg.motion.no_keybody)
  File "/home/nuli/rl/expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 157, in _load_motion
    self._motion_lib = MotionLib(motion_file=motion_file,
  File "/home/nuli/rl/expressive-humanoid/ASE/ase/utils/motion_lib.py", line 116, in __init__
    self.serialize_motions(pkl_file)
  File "/home/nuli/rl/expressive-humanoid/ASE/ase/utils/motion_lib.py", line 356, in serialize_motions
    with open(pkl_file, 'wb') as outp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/nuli/rl/expressive-humanoid/ASE/ase/poselib/data/pkl/motions_autogen_all_no_run_jump.pkl'
wandb: 🚀 View run 000-01-some_descriptions_of_run at: https://wandb.ai/nuli/humanoid/runs/s1gnoac8
wandb: ⭐️ View project at: https://wandb.ai/nuli/humanoid
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 4 other file(s)
wandb: Find logs at: ../../logs/wandb/run-20240906_144256-s1gnoac8/logs
wandb: WARNING The new W&B backend becomes opt-out in version 0.18.0; try it out with `wandb.require("core")`! See https://wandb.me/wandb-core for more information.

how to produce the correspoinding pkl files

**Comment by Mr-Zqr** [comment]
Hi there, I am suffering from the same error. How did you solve it?

**Comment by davidmao829** [comment]
Try changing the regen_pkl parameter！

**Comment by Mr-Zqr** [comment]
> Try changing the regen_pkl parameter！

Thanks! I changed the `regen_pkl` param in `./legged_gym/legged_gym/envs/h1/h1_mimic_config.py`  :68. And then manually created the `pkl` folder. Now it's working fine.

**Comment by LQ0212** [comment]
@Mr-Zqr hi I changed the regen_pkl param and created the pkl folder into true but the error about No such file or directory: '/home/liqi/legrobot_gym/expressive-humanoid/ASE/ase/poselib/data/pkl/motions_autogen_walk.pkl'
still alive, do i need to rerun some step to get the pkl files, thanks

**Comment by Mr-Zqr** [comment]
> [@Mr-Zqr](https://github.com/Mr-Zqr) hi I changed the regen_pkl param and created the pkl folder into true but the error about No such file or directory: '/home/liqi/legrobot_gym/expressive-humanoid/ASE/ase/poselib/data/pkl/motions_autogen_walk.pkl' still alive, do i need to rerun some step to get the pkl files, thanks

Hi there! I'm not sure what happened in your case. To my knowledge, if `regen_pkl` is set to True and the pkl folder exits, the program should try to load .npy files and generate the corresponding .pkl automatically. 

The code related to loading motions is in `ASE/ase/utils/motion_lib.py`, maybe you can do a deeper check. Best of luck!

**Comment by LQ0212** [comment]
@Mr-Zqr  Thanks for your help. I solve this problem successfully, `regen_pkl` is need set to false in `h1_minic.config` but the problem still have. I check the code in `motion_lib.py` and set the regen_pkl in this file then don't need the .pkl files.
