### ISSUE TITLE
Some problems dealing with `key_body_ids`

### ISSUE THREAD

**Issue by songsq21** [chengxuxin/expressive-humanoid#4]
I was running the default training command
`python train.py xxx-xx-some_descriptions_of_run --device cuda:0 --entity WANDB_ENTITY`
when I encountered with errors with `key_body_ids`:
in `_load_motion()` in `legged_gym/legged_gym/envs/h1/h1_mimic.py`, line 158:
```
self._motion_lib = MotionLib(motion_file=motion_file,
                             dof_body_ids=self._dof_body_ids,
                             dof_offsets=self._dof_offsets,
                             key_body_ids=self._key_body_ids.cpu().numpy(),
                             device=self.device, 
                             no_keybody=no_keybody, 
                             regen_pkl=self.cfg.motion.regen_pkl)
```
where `self._key_body_ids = torch.tensor([3, 6, 9, 12], device=self.device)`,
however in line 397-415, in `update_demo_obs`:
```
self._curr_demo_keybody[:] = local_key_body_pos[:, self._key_body_ids_sim_subset].view(self.num_envs, self._motion_num_future_steps, self._num_key_bodies, 3)[:, 0, :, :]
```
where the error shows `self._motion_num_future_steps` is out of range of 4, where it is `[6, 7, 8, 9, 10, 11]`
**I guess there is a reindexing of the whole tensor while in `get_motion_state` seems to use the indexes of the original tensor.**
The error logging:
```
Traceback (most recent call last):
  File "train.py", line 72, in <module>
    train(args)
  File "train.py", line 65, in train
    env, env_cfg = task_registry.make_env(name=args.task, args=args)
  File ".../expressive-humanoid/legged_gym/legged_gym/utils/task_registry.py", line 101, in make_env
    env = task_class(   cfg=env_cfg,
  File ".../expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 62, in __init__
    self.post_physics_step()
  File ".../expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 346, in post_physics_step
    self.update_demo_obs()
  File ".../expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 408, in update_demo_obs
    self._curr_demo_keybody[:] = local_key_body_pos[:, self._key_body_ids_sim_subset].view(self.num_envs, self._motion_num_future_steps, self._num_key_bodies, 3)[:, 0, :, :]
IndexError: index 6 is out of bounds for dimension 0 with size 4
```

**Comment by songsq21** [comment]
Sorry I am dumb

**Comment by songsq21** [comment]
Sorry I am dumb

**Comment by edpsw** [comment]
Hello, I have also encountered this problem. How did you solve it
```
Exception has occurred: IndexError
index 6 is out of bounds for dimension 0 with size 4
  File "/home/mycode/exp-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 404, in update_demo_obs
    self._curr_demo_keybody[:] = local_key_body_pos[:, self._key_body_ids_sim_subset].view(self.num_envs, self._motion_num_future_steps, self._num_key_bodies, 3)[:, 0, :, :]
  File "/home/mycode/exp-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 344, in post_physics_step
    self.update_demo_obs()
  File "/home/mycode/exp-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 61, in __init__
    self.post_physics_step()
  File "/home/mycode/exp-humanoid/legged_gym/legged_gym/utils/task_registry.py", line 98, in make_env
    env = task_class(   cfg=env_cfg,
  File "/home/mycode/exp-humanoid/legged_gym/legged_gym/scripts/train.py", line 71, in train
    env, env_cfg = task_registry.make_env(name=args.task, args=args)
  File "/home/mycode/exp-humanoid/legged_gym/legged_gym/scripts/train.py", line 78, in <module>
    train(args)
IndexError: index 6 is out of bounds for dimension 0 with size 4
```

**Comment by SakuBorder** [comment]
> 当我运行默认训练命令时， `python train.py xxx-xx-some_descriptions_of_run --device cuda:0 --entity WANDB_ENTITY` 遇到以下错误`key_body_ids`： 在，第 158 行：`_load_motion()``legged_gym/legged_gym/envs/h1/h1_mimic.py`
> 
> ```
> self._motion_lib = MotionLib(motion_file=motion_file,
>                              dof_body_ids=self._dof_body_ids,
>                              dof_offsets=self._dof_offsets,
>                              key_body_ids=self._key_body_ids.cpu().numpy(),
>                              device=self.device, 
>                              no_keybody=no_keybody, 
>                              regen_pkl=self.cfg.motion.regen_pkl)
> ```
> 
> 其中`self._key_body_ids = torch.tensor([3, 6, 9, 12], device=self.device)`， 然而在第 397-415 行中，在`update_demo_obs`：
> 
> ```
> self._curr_demo_keybody[:] = local_key_body_pos[:, self._key_body_ids_sim_subset].view(self.num_envs, self._motion_num_future_steps, self._num_key_bodies, 3)[:, 0, :, :]
> ```
> 
> 错误显示`self._motion_num_future_steps`超出了 4 的范围，我猜测是`[6, 7, 8, 9, 10, 11]` **整个张量被重新索引了，而`get_motion_state`似乎使用了原始张量的索引。** 错误日志如下：
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 72, in <module>
>     train(args)
>   File "train.py", line 65, in train
>     env, env_cfg = task_registry.make_env(name=args.task, args=args)
>   File ".../expressive-humanoid/legged_gym/legged_gym/utils/task_registry.py", line 101, in make_env
>     env = task_class(   cfg=env_cfg,
>   File ".../expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 62, in __init__
>     self.post_physics_step()
>   File ".../expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 346, in post_physics_step
>     self.update_demo_obs()
>   File ".../expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 408, in update_demo_obs
>     self._curr_demo_keybody[:] = local_key_body_pos[:, self._key_body_ids_sim_subset].view(self.num_envs, self._motion_num_future_steps, self._num_key_bodies, 3)[:, 0, :, :]
> IndexError: index 6 is out of bounds for dimension 0 with size 4
> ```

"I hope you don't mind me asking, but could you kindly share how you resolved this issue? I’m very much looking forward to your reply."

**Comment by song-siqi** [comment]
I didn't remember how I solved this but actually you can try by simply editing the index process here to match with the correct indexes for the joints/bodies lol

> > 当我运行默认训练命令时， `python train.py xxx-xx-some_descriptions_of_run --device cuda:0 --entity WANDB_ENTITY` 遇到以下错误`key_body_ids`： 在，第 158 行：`` _load_motion()``legged_gym/legged_gym/envs/h1/h1_mimic.py ``
> > ```
> > self._motion_lib = MotionLib(motion_file=motion_file,
> >                              dof_body_ids=self._dof_body_ids,
> >                              dof_offsets=self._dof_offsets,
> >                              key_body_ids=self._key_body_ids.cpu().numpy(),
> >                              device=self.device, 
> >                              no_keybody=no_keybody, 
> >                              regen_pkl=self.cfg.motion.regen_pkl)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 其中`self._key_body_ids = torch.tensor([3, 6, 9, 12], device=self.device)`， 然而在第 397-415 行中，在`update_demo_obs`：
> > ```
> > self._curr_demo_keybody[:] = local_key_body_pos[:, self._key_body_ids_sim_subset].view(self.num_envs, self._motion_num_future_steps, self._num_key_bodies, 3)[:, 0, :, :]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 错误显示`self._motion_num_future_steps`超出了 4 的范围，我猜测是`[6, 7, 8, 9, 10, 11]` **整个张量被重新索引了，而`get_motion_state`似乎使用了原始张量的索引。** 错误日志如下：
> > ```
> > Traceback (most recent call last):
> >   File "train.py", line 72, in <module>
> >     train(args)
> >   File "train.py", line 65, in train
> >     env, env_cfg = task_registry.make_env(name=args.task, args=args)
> >   File ".../expressive-humanoid/legged_gym/legged_gym/utils/task_registry.py", line 101, in make_env
> >     env = task_class(   cfg=env_cfg,
> >   File ".../expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 62, in __init__
> >     self.post_physics_step()
> >   File ".../expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 346, in post_physics_step
> >     self.update_demo_obs()
> >   File ".../expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 408, in update_demo_obs
> >     self._curr_demo_keybody[:] = local_key_body_pos[:, self._key_body_ids_sim_subset].view(self.num_envs, self._motion_num_future_steps, self._num_key_bodies, 3)[:, 0, :, :]
> > IndexError: index 6 is out of bounds for dimension 0 with size 4
> > ```
> 
> "I hope you don't mind me asking, but could you kindly share how you resolved this issue? I’m very much looking forward to your reply."

**Comment by SakuBorder** [comment]
> I didn't remember how I solved this but actually you can try by simply editing the index process here to match with the correct indexes for the joints/bodies lol
> 
> > > 当我运行默认训练命令时， `python train.py xxx-xx-some_descriptions_of_run --device cuda:0 --entity WANDB_ENTITY` 遇到以下错误`key_body_ids`： 在，第 158 行：` _load_motion()`legged_gym/legged_gym/envs/h1/h1_mimic.py ``
> > > ```
> > > self._motion_lib = MotionLib(motion_file=motion_file,
> > >                              dof_body_ids=self._dof_body_ids,
> > >                              dof_offsets=self._dof_offsets,
> > >                              key_body_ids=self._key_body_ids.cpu().numpy(),
> > >                              device=self.device, 
> > >                              no_keybody=no_keybody, 
> > >                              regen_pkl=self.cfg.motion.regen_pkl)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 其中`self._key_body_ids = torch.tensor([3, 6, 9, 12], device=self.device)`， 然而在第 397-415 行中，在`update_demo_obs`：
> > > ```
> > > self._curr_demo_keybody[:] = local_key_body_pos[:, self._key_body_ids_sim_subset].view(self.num_envs, self._motion_num_future_steps, self._num_key_bodies, 3)[:, 0, :, :]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 错误显示`self._motion_num_future_steps`超出了 4 的范围，我猜测是`[6, 7, 8, 9, 10, 11]` **整个张量被重新索引了，而`get_motion_state`似乎使用了原始张量的索引。** 错误日志如下：
> > > ```
> > > Traceback (most recent call last):
> > >   File "train.py", line 72, in <module>
> > >     train(args)
> > >   File "train.py", line 65, in train
> > >     env, env_cfg = task_registry.make_env(name=args.task, args=args)
> > >   File ".../expressive-humanoid/legged_gym/legged_gym/utils/task_registry.py", line 101, in make_env
> > >     env = task_class(   cfg=env_cfg,
> > >   File ".../expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 62, in __init__
> > >     self.post_physics_step()
> > >   File ".../expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 346, in post_physics_step
> > >     self.update_demo_obs()
> > >   File ".../expressive-humanoid/legged_gym/legged_gym/envs/h1/h1_mimic.py", line 408, in update_demo_obs
> > >     self._curr_demo_keybody[:] = local_key_body_pos[:, self._key_body_ids_sim_subset].view(self.num_envs, self._motion_num_future_steps, self._num_key_bodies, 3)[:, 0, :, :]
> > > IndexError: index 6 is out of bounds for dimension 0 with size 4
> > > ```
> > 
> > 
> > "I hope you don't mind me asking, but could you kindly share how you resolved this issue? I’m very much looking forward to your reply."

Thank you very much. I’ll try expanding self._key_body_ids to see if it affects the results.
